- src/app/components/NewItineraryModal.jsx
- src/app/components/SearchBar.jsx
- src/app/dashboard/page.jsx
- src/app/page.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/app/plan/new/page.jsx
- src/app/plan/page.jsx
- src/lib/base64Utils.js
- Added data passdown
- Added dynamic routing
- Added custom url generation
- Added required/optional forms
- Made modal functional -> leads to new dynamic page when used
> Add data persistence & dynamic routing

- src/app/components/Footer.jsx
- src/app/components/NewItineraryModal.jsx
- src/app/components/SearchBar.jsx
- src/app/components/TitleTypeWriter.jsx
- src/app/components/TopNavBar.jsx
- src/app/context/TripDataContext.js
- src/app/layout.jsx
- src/app/page.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/app/plan/new/page.jsx
- state logic refactored into higher level context (shared between all pages)
- removes the need to prop drill initial setup & duplication of code
- removed unused React imports as those are implicit & other unused imports
> Refactor state logic

- src/app/components/DateRangeCalendar.jsx
- src/app/components/NewItineraryModal.jsx
- src/app/context/TripDataContext.js
- src/app/page.jsx
- Removed unused imports from DateRangeCalendar
- Removed prop drilling setState methods from NewItineraryModel -> DateRangeModel
- Added default image alt tag to get rid of the error popping up in console
- Connected the date range selection to the tripData context
- Changed the styling of MMM/dd/yyyy to MMM/dd/yyyy -> MM/dd/yyyy - MM/dd/yyyy (optional - can be changed back depending on group preference)
- Changed (Required) to (required) to match with the other fields for Date Range placeholder(value)
> Date range calendar merge fix

- src/app/account/settings/page.jsx
- src/app/api/trips/delete/route.js
- src/app/api/users/[clerkId]/route.js
- src/app/api/users/update/route.js
- src/app/components/NewItineraryModal.jsx
- src/app/plan/new/page.jsx
- src/lib/api.js
- src/lib/db/createTrip.js
- src/lib/db/fetchUser.js
- src/lib/db/updateUser.js
- added update user route and /account/settings page - working implementation but potentially needs to be expanded depending on the data we're planning on storing
- added skeletons for basic routing for trips/etc
- added some todo comments
- shortened customUrl length in current code (in preparation for storing it in tripData and into the db to have a reference)
> Add update user crud route

- src/app/components/DatePicker.jsx
- src/app/components/DateRangeCalendar.jsx
- src/app/components/NewItineraryModal.jsx
- src/app/context/TripDataContext.js
- src/app/dashboard/page.jsx
- src/app/page.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/app/plan/new/page.jsx
- src/lib/api.js
- src/lib/db/createTrip.js
- src/lib/resetTripData.js
> Trip creation set up

- src/app/components/SearchBar.jsx
- src/app/dashboard/page.jsx
- src/app/page.jsx
> Moved dashboard to root page

- src/app/components/DatePicker.jsx
- src/app/components/DateRangeCalendar.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/lib/populateTripData.js
- added loading of existing trips based on url when the unique url is visited
- fixed the conversion of date objects into UTC locale date strings
> Add trip loader from db

- prisma/schema.prisma
- src/lib/db/days/createDay.js
- src/lib/db/days/deleteDay.js
- src/lib/db/days/updateDay.js
- src/lib/db/trips/createTrip.js
- src/lib/db/trips/updateTrip.js
- updated db schema to include cascading deletes + new fields in trip/day/event
- trip new fields : imageUrl, description, title
- day new field: lodging
- event new field: description
- fixed trip/day creation/update values
> Update db schema

- prisma/migrations/20240107044646_added_cascading_delete/migration.sql
> migrated new prisma schema changes

- src/app/context/TripDataContext.js
- src/app/dashboard/page.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/lib/populateTripData.js
- src/lib/resetTripData.js
- add some more temp forms to modify the existing trip data 
- add days array to tripdata context
> Add extra fields to encodedurl

- src/app/api/trips/[url]/days/route.js
- src/app/components/DatePicker.jsx
- src/app/components/DateRangeCalendar.jsx
- src/app/components/Days.jsx
- src/app/components/EditDays.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/lib/api.js
- src/lib/createAllDays.js
- src/lib/db/days/createDay.js
- src/lib/db/trips/createTrip.js
- src/lib/db/trips/fetchTrip.js
- src/lib/populateTripData.js
- Added fetching days by active trip url & added the logic for rendering the fetched days onto the page (currently re-runs when the useEffect is called, consider looking into changing this into a single run)
- Removed utc date rendering because it was actually not correct
- Added TODO messages in the code
> Implemented fetching and rendering of days to the encodedUrl page

- src/app/components/EditDays.jsx
- src/app/components/SearchBar.jsx
- added places autocomplete search bar to events
> Add places to events

- src/app/api/events/delete/route.js
- src/app/api/events/new/route.js
- src/app/components/CompleteDays.jsx
- src/app/components/Days.jsx
- src/app/components/EditDays.jsx
- src/lib/api.js
- src/lib/db/events/createEvent.js
- src/lib/db/events/deleteEvent.js
- Added delete button to each rendered event 
- Added loading animation to create/delete events
- Moved state up to CompleteDays to share data
- Fixed implementation of handleCreateTrip to return the right data type
> Added delete event button

- src/app/components/Days.jsx
- src/app/plan/[encodedUrl]/page.jsx
- removed some of the todo comments & other unused comments/imports
> Removing some of the unused comments/imports

- src/app/components/CompleteDays.jsx
- src/app/components/DatePicker.jsx
- src/app/components/Days.jsx
- src/app/components/EditDays.jsx
- src/app/plan/[encodedUrl]/page.jsx
- added checks for if the current user is signed in & if the current user is the same as the trip  owner (commented out for now for development purposes)
> Added current user checks for editting pages that are saved already

- src/app/plan/[encodedUrl]/page.jsx
- src/middleware.jsx
- added api routes & plan page to middleware public routes
> Add to middleware routes to enable offline viewing

- src/app/api/events/update/route.js
- src/app/components/Collapsible.jsx
- src/app/components/Days.jsx
- src/app/components/EditDays.jsx
- src/app/components/SearchBar.jsx
- src/app/plan/[encodedUrl]/page.jsx
- added arrow to the collapsible component that has transform rotate effects on click
- fixed event updating location/notes to sync with visibleEvents as well as DB
- added event location to the displayed event title
- added automatic closing of all opened details when switching from edit mode to normal mode
> Collapsible arrow

- src/app/components/SearchBar.jsx
- src/app/plan/new/page.jsx
- required places autocomplete selection on new plan creation
> Implemented state checking for if places autocomplete was used

- package-lock.json
- src/app/components/Banner.jsx
- src/app/components/Days.jsx
- src/app/components/SuggestionBox.jsx
- src/app/page.jsx
- fixed the sizing issue on the root page ( still has a minor issue with the overflow
- added default starting new event dates back
- refactored the google places nearby search to filter based off of types array rather than location name
> Bug fix events refactor google places search

- src/app/components/Days.jsx
- src/app/components/EditDays.jsx
- fixed issue with new event not showing when events was completely empty
> Fixed partial bug on creating new events

- src/app/plan/[encodedUrl]/page.jsx
- src/app/plan/new/page.jsx
- Replaces save button for non signed in user & removed the mandatory redirect if not signed in
> Allow trip creation block saving

- next.config.js
- package-lock.json
- package.json
- prisma/migrations/20240116155924_added_order_to_event/migration.sql
- prisma/schema.prisma
- src/app/components/Days.jsx
- src/app/components/Event.jsx
- src/app/plan/[encodedUrl]/page.jsx
- src/lib/db/events/updateEvent.js
- src/lib/populateTripData.js
- added drag and order functionality 
- fixed some naming issues on the html attributes for the encodedUrl page
> Drag and order

- src/app/components/Suggestion.jsx
- src/app/components/SuggestionBox.jsx
- src/app/plan/[encodedUrl]/page.jsx
- suggestions carousel added
- improved restaurant suggestions 
- styled the carousel results to be in a card format
> Suggestions box styling

- src/app/components/TopNavBar.jsx
- src/app/dashboard/page.jsx
User can click the trip banner images populated in the dashboard to go to their individual trips.
> Dashboard functionality
